### ISSUE TITLE
cloudflare のビルドが定期実行されていない

### ISSUE THREAD

**Issue by kei1-st** [kei1-st/kassuikai#40]
以下の処理を actions.yaml に追加する

```
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```

参考：https://journal.manasas.dev/entry/2023/12/03/162801
